// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD00sofD1eyiS0cLtI-QwgfO7U0FETT5Y8',
    appId: '1:744644128541:web:aa9e2798f3598c3402bbf4',
    messagingSenderId: '744644128541',
    projectId: 'tracker-f7299',
    authDomain: 'tracker-f7299.firebaseapp.com',
    storageBucket: 'tracker-f7299.appspot.com',
    measurementId: 'G-DYXYN9VNWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0f8NLRfp4mFaU_7JKbQPXw00m9LDfKJc',
    appId: '1:744644128541:android:44cd0ca7a6f2d15c02bbf4',
    messagingSenderId: '744644128541',
    projectId: 'tracker-f7299',
    storageBucket: 'tracker-f7299.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD00sofD1eyiS0cLtI-QwgfO7U0FETT5Y8',
    appId: '1:744644128541:web:2b536aaaab00c7ec02bbf4',
    messagingSenderId: '744644128541',
    projectId: 'tracker-f7299',
    authDomain: 'tracker-f7299.firebaseapp.com',
    storageBucket: 'tracker-f7299.appspot.com',
    measurementId: 'G-5NW416BXN2',
  );
}